name: Build Probackup on Linux

on:
  push:
    branches:
      - "**"
  # Runs triggered by pull requests are disabled to prevent executing potentially unsafe code from public pull requests
  # pull_request:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        pg_version: [13, 14, 15]

    runs-on:
      - ubuntu-20.04

    env:
      PG_VERSION: ${{ matrix.pg_version }}
      PG_BRANCH: ${{ matrix.pg_version == 15 && 'master' || format('REL_{0}_STABLE', matrix.pg_version) }}
      PTRACK_PATCH_PG_BRANCH: ${{ matrix.pg_version == 15 && 'master' || format('REL_{0}_STABLE', matrix.pg_version) }}

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          cp travis/* .
          ./make_dockerfile.sh
          docker-compose build

      - name: Run tests
        run: |
          docker-compose run tests

    continue-on-error: ${{ matrix.pg_version == 15 }}

